# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "byebug"
gem "sinatra"
gem "activerecord"
gem "pg"
gem "dotenv", groups: [:development, :test]
# gem "segregato", path: "../segregato" # for test in localhost
gem "segregato", git: "git@github.com:solehudinmq/segregato.git", branch: "main"
gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
